author: DerFlash
database: true
generator: http://dinnerbone.com/minecraft/tools/pluginator/
main: me.derflash.plugins.cnbiomeedit.CNBiomeEdit
name: BiomeEdit
startup: postworld
url: http://www.cube-nation.de/
version: '1.1-SNAPSHOT'
commands:
    biome:
        description: Manage your biomes
        usage: /biome help for more information
        aliases: [be, biomeedit]
        